from __future__ import annotations

from typing import TypedDict


class StandardUom(TypedDict):
	name: str
	uom_name: str
	display_name: str
	symbol: str | None
	must_be_whole_number: int
	description: str
	aliases: tuple[str, ...]


STANDARD_UOMS: tuple[StandardUom, ...] = (
	{
		"name": "Nos",
		"uom_name": "Nos",
		"display_name": "件",
		"symbol": "件",
		"must_be_whole_number": 1,
		"description": "最通用的单件计数单位。",
		"aliases": ("NO", "PCS", "PC", "PIECE", "PIECES"),
	},
	{
		"name": "Unit",
		"uom_name": "Unit",
		"display_name": "个",
		"symbol": "个",
		"must_be_whole_number": 1,
		"description": "通用个体数量单位。",
		"aliases": (),
	},
	{
		"name": "Pair",
		"uom_name": "Pair",
		"display_name": "对",
		"symbol": "对",
		"must_be_whole_number": 1,
		"description": "成对商品计数单位。",
		"aliases": (),
	},
	{
		"name": "Set",
		"uom_name": "Set",
		"display_name": "套",
		"symbol": "套",
		"must_be_whole_number": 1,
		"description": "成套商品计数单位。",
		"aliases": ("SETS",),
	},
	{
		"name": "Group",
		"uom_name": "Group",
		"display_name": "组",
		"symbol": "组",
		"must_be_whole_number": 1,
		"description": "成组商品计数单位。",
		"aliases": (),
	},
	{
		"name": "Sheet",
		"uom_name": "Sheet",
		"display_name": "张",
		"symbol": "张",
		"must_be_whole_number": 1,
		"description": "纸张、薄片计数单位。",
		"aliases": (),
	},
	{
		"name": "Piece",
		"uom_name": "Piece",
		"display_name": "片",
		"symbol": "片",
		"must_be_whole_number": 1,
		"description": "片状商品计数单位。",
		"aliases": (),
	},
	{
		"name": "Strip",
		"uom_name": "Strip",
		"display_name": "条",
		"symbol": "条",
		"must_be_whole_number": 1,
		"description": "条状商品计数单位。",
		"aliases": (),
	},
	{
		"name": "Block",
		"uom_name": "Block",
		"display_name": "块",
		"symbol": "块",
		"must_be_whole_number": 1,
		"description": "块状商品计数单位。",
		"aliases": (),
	},
	{
		"name": "Box",
		"uom_name": "Box",
		"display_name": "箱",
		"symbol": "箱",
		"must_be_whole_number": 1,
		"description": "整箱包装单位。",
		"aliases": ("BOXES",),
	},
	{
		"name": "Carton",
		"uom_name": "Carton",
		"display_name": "纸箱",
		"symbol": "箱",
		"must_be_whole_number": 1,
		"description": "纸箱包装单位。",
		"aliases": (),
	},
	{
		"name": "Case",
		"uom_name": "Case",
		"display_name": "箱装",
		"symbol": "箱",
		"must_be_whole_number": 1,
		"description": "箱装商品计量单位。",
		"aliases": ("CASES",),
	},
	{
		"name": "Pack",
		"uom_name": "Pack",
		"display_name": "包",
		"symbol": "包",
		"must_be_whole_number": 1,
		"description": "成包包装单位。",
		"aliases": ("PACKS",),
	},
	{
		"name": "Bag",
		"uom_name": "Bag",
		"display_name": "袋",
		"symbol": "袋",
		"must_be_whole_number": 1,
		"description": "袋装单位。",
		"aliases": ("BAGS",),
	},
	{
		"name": "Sack",
		"uom_name": "Sack",
		"display_name": "麻袋",
		"symbol": "袋",
		"must_be_whole_number": 1,
		"description": "大袋包装单位。",
		"aliases": (),
	},
	{
		"name": "Bundle",
		"uom_name": "Bundle",
		"display_name": "捆",
		"symbol": "捆",
		"must_be_whole_number": 1,
		"description": "捆装商品单位。",
		"aliases": (),
	},
	{
		"name": "Roll",
		"uom_name": "Roll",
		"display_name": "卷",
		"symbol": "卷",
		"must_be_whole_number": 1,
		"description": "卷状商品单位。",
		"aliases": ("ROLLS",),
	},
	{
		"name": "Tray",
		"uom_name": "Tray",
		"display_name": "盘",
		"symbol": "盘",
		"must_be_whole_number": 1,
		"description": "托盘、蛋盘等包装单位。",
		"aliases": (),
	},
	{
		"name": "Pallet",
		"uom_name": "Pallet",
		"display_name": "托盘",
		"symbol": "托",
		"must_be_whole_number": 1,
		"description": "仓储整托计量单位。",
		"aliases": (),
	},
	{
		"name": "Crate",
		"uom_name": "Crate",
		"display_name": "筐",
		"symbol": "筐",
		"must_be_whole_number": 1,
		"description": "周转筐单位。",
		"aliases": (),
	},
	{
		"name": "Bottle",
		"uom_name": "Bottle",
		"display_name": "瓶",
		"symbol": "瓶",
		"must_be_whole_number": 1,
		"description": "瓶装商品单位。",
		"aliases": ("BOTTLES",),
	},
	{
		"name": "Jar",
		"uom_name": "Jar",
		"display_name": "罐",
		"symbol": "罐",
		"must_be_whole_number": 1,
		"description": "罐装商品单位。",
		"aliases": (),
	},
	{
		"name": "Can",
		"uom_name": "Can",
		"display_name": "听",
		"symbol": "听",
		"must_be_whole_number": 1,
		"description": "听装商品单位。",
		"aliases": (),
	},
	{
		"name": "Barrel",
		"uom_name": "Barrel",
		"display_name": "桶",
		"symbol": "桶",
		"must_be_whole_number": 1,
		"description": "桶装商品单位。",
		"aliases": ("BARREL (OIL)", "BARREL(BEER)"),
	},
	{
		"name": "Drum",
		"uom_name": "Drum",
		"display_name": "大桶",
		"symbol": "桶",
		"must_be_whole_number": 1,
		"description": "大桶液体或原料单位。",
		"aliases": (),
	},
	{
		"name": "Cup",
		"uom_name": "Cup",
		"display_name": "杯",
		"symbol": "杯",
		"must_be_whole_number": 1,
		"description": "杯装商品单位。",
		"aliases": (),
	},
	{
		"name": "Kg",
		"uom_name": "Kg",
		"display_name": "千克",
		"symbol": "kg",
		"must_be_whole_number": 0,
		"description": "常规重量单位。",
		"aliases": ("KGS",),
	},
	{
		"name": "Gram",
		"uom_name": "Gram",
		"display_name": "克",
		"symbol": "g",
		"must_be_whole_number": 0,
		"description": "小重量单位。",
		"aliases": ("G", "GRAMS"),
	},
	{
		"name": "Milligram",
		"uom_name": "Milligram",
		"display_name": "毫克",
		"symbol": "mg",
		"must_be_whole_number": 0,
		"description": "极小重量单位。",
		"aliases": ("MG",),
	},
	{
		"name": "Tonne",
		"uom_name": "Tonne",
		"display_name": "吨",
		"symbol": "t",
		"must_be_whole_number": 0,
		"description": "大宗重量单位。",
		"aliases": ("TON",),
	},
	{
		"name": "Jin",
		"uom_name": "Jin",
		"display_name": "斤",
		"symbol": "斤",
		"must_be_whole_number": 0,
		"description": "本地化零售重量单位。",
		"aliases": (),
	},
	{
		"name": "Pound",
		"uom_name": "Pound",
		"display_name": "磅",
		"symbol": "lb",
		"must_be_whole_number": 0,
		"description": "英制重量单位。",
		"aliases": (),
	},
	{
		"name": "Litre",
		"uom_name": "Litre",
		"display_name": "升",
		"symbol": "L",
		"must_be_whole_number": 0,
		"description": "常规体积单位。",
		"aliases": ("L", "LTR", "LITER"),
	},
	{
		"name": "Millilitre",
		"uom_name": "Millilitre",
		"display_name": "毫升",
		"symbol": "mL",
		"must_be_whole_number": 0,
		"description": "小体积单位。",
		"aliases": ("ML", "MILLILITER"),
	},
	{
		"name": "Cubic Meter",
		"uom_name": "Cubic Meter",
		"display_name": "立方米",
		"symbol": "m3",
		"must_be_whole_number": 0,
		"description": "大体积计量单位。",
		"aliases": ("CUBIC METER", "CUBICMETRE", "CUBIC METRE"),
	},
	{
		"name": "Meter",
		"uom_name": "Meter",
		"display_name": "米",
		"symbol": "m",
		"must_be_whole_number": 0,
		"description": "通用长度单位。",
		"aliases": ("M", "METRE"),
	},
	{
		"name": "Centimeter",
		"uom_name": "Centimeter",
		"display_name": "厘米",
		"symbol": "cm",
		"must_be_whole_number": 0,
		"description": "小长度单位。",
		"aliases": ("CM", "CENTIMETRE"),
	},
	{
		"name": "Millimeter",
		"uom_name": "Millimeter",
		"display_name": "毫米",
		"symbol": "mm",
		"must_be_whole_number": 0,
		"description": "更小长度单位。",
		"aliases": ("MM", "MILLIMETRE"),
	},
	{
		"name": "Kilometer",
		"uom_name": "Kilometer",
		"display_name": "千米",
		"symbol": "km",
		"must_be_whole_number": 0,
		"description": "长距离单位。",
		"aliases": ("KM", "KILOMETRE"),
	},
	{
		"name": "Yard",
		"uom_name": "Yard",
		"display_name": "码",
		"symbol": "yd",
		"must_be_whole_number": 0,
		"description": "英制长度单位。",
		"aliases": ("YD", "YDS"),
	},
	{
		"name": "Foot",
		"uom_name": "Foot",
		"display_name": "英尺",
		"symbol": "ft",
		"must_be_whole_number": 0,
		"description": "英制长度单位。",
		"aliases": ("FT",),
	},
	{
		"name": "Inch",
		"uom_name": "Inch",
		"display_name": "英寸",
		"symbol": "in",
		"must_be_whole_number": 0,
		"description": "英制尺寸单位。",
		"aliases": ("IN",),
	},
	{
		"name": "Square Meter",
		"uom_name": "Square Meter",
		"display_name": "平方米",
		"symbol": "m2",
		"must_be_whole_number": 0,
		"description": "面积计量单位。",
		"aliases": ("SQUARE METER", "SQUARE METRE"),
	},
	{
		"name": "Square Foot",
		"uom_name": "Square Foot",
		"display_name": "平方英尺",
		"symbol": "ft2",
		"must_be_whole_number": 0,
		"description": "英制面积计量单位。",
		"aliases": ("SQUARE FOOT",),
	},
	{
		"name": "Day",
		"uom_name": "Day",
		"display_name": "天",
		"symbol": "天",
		"must_be_whole_number": 0,
		"description": "按天计量的服务或周期单位。",
		"aliases": ("D",),
	},
	{
		"name": "Week",
		"uom_name": "Week",
		"display_name": "周",
		"symbol": "周",
		"must_be_whole_number": 0,
		"description": "按周计量的服务或周期单位。",
		"aliases": ("WK",),
	},
	{
		"name": "Month",
		"uom_name": "Month",
		"display_name": "月",
		"symbol": "月",
		"must_be_whole_number": 0,
		"description": "按月计量的服务或周期单位。",
		"aliases": ("MON",),
	},
	{
		"name": "Hour",
		"uom_name": "Hour",
		"display_name": "小时",
		"symbol": "h",
		"must_be_whole_number": 0,
		"description": "按小时计量的服务或工时单位。",
		"aliases": ("H",),
	},
)


STANDARD_UOM_MAP = {row["name"]: row for row in STANDARD_UOMS}

STANDARD_UOM_DISPLAY_ALIASES = {
	alias.upper(): row["display_name"]
	for row in STANDARD_UOMS
	for alias in (row["name"], row["uom_name"], *row["aliases"])
}

TEST_UOM_PREFIXES = ("HTTP-UOM-", "HTTP-RANGE-UOM-")
